[package]
name = "strategies"
cairo-version = "2.3.1"
version.workspace = true

[dependencies]
starknet = "2.3.1"
amm = { path = "../amm" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.12.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
  'amm::contracts::*',
#  'openzeppelin::token::erc20::erc20::ERC20',
]

[cairo]
sierra-replace-ids = true

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 88888