[package]
name = "strategies"
cairo-version = "2.5.4"
version.workspace = true
edition.workspace = true

[dependencies]
starknet = "2.5.4"
amm = { path = "../amm" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.19.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
  'amm::contracts::*',
#  'openzeppelin::token::erc20::erc20::ERC20',
]

[cairo]
sierra-replace-ids = true

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 88888

[[tool.snforge.fork]]
name = "MAINNET"
url = 'https://starknet-mainnet.g.alchemy.com/v2/W0Et338bj6xJ9-gP2Obx32k1FYl6nTxD'
block_id.tag = "Latest"