[package]
name = "sphinx"
version.workspace = true

[dependencies]
starknet.workspace = true
amm = { path = "amm"}
strategies = { path = "strategies"}

[workspace]
members = [
    "amm",
    "strategies",
]

[workspace.dependencies]
starknet = "2.3.0"

[workspace.package]
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 88888