[package]
name = "haiko_amm"
cairo-version = "2.6.3"
version = "2.0.0"
edition = '2023_11'

[dependencies]
starknet = "2.6.3"
haiko_lib = { git = "https://github.com/haiko-xyz/library.git", branch = "v2.0.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.11.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.21.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = [
  'haiko_lib::mocks::erc20::ERC20'
]


[cairo]
sierra-replace-ids = true

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 88888

[[tool.snforge.fork]]
name = "MAINNET"
url = 'https://free-rpc.nethermind.io/mainnet-juno'
block_id.tag = "Latest"

[[tool.snforge.fork]]
name = "SEPOLIA"
url = 'https://free-rpc.nethermind.io/sepolia-juno'
block_id.tag = "Latest"