[package]
name = "amm"
cairo-version = "2.5.4"
version.workspace = true
edition.workspace = true

[dependencies]
starknet = "2.5.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.19.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 88888

[[tool.snforge.fork]]
name = "TESTNET"
url = 'https://starknet-testnet.public.blastapi.io'
block_id.tag = "Latest"