[package]
name = "amm"
cairo-version = "2.3.0"
version.workspace = true

[dependencies]
starknet = "2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.9.1" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0-beta.0" }

[lib]

[[target.starknet-contract]]
build-external-contracts = ['openzeppelin::token::erc20::erc20::ERC20']
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[cairo]
sierra-replace-ids = true

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 8888