name: Tests and linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SCARB_VERSION: 2.3.0
  SNFORGE_VERSION: 0.9.1

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v ${{ env.SCARB_VERSION }}

      - name: Setup Foundry
        run: |
          curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh -s -- -v ${{ env.SNFORGE_VERSION }}

      - name: Build and test `amm`
        working-directory: ./amm
        run: |
          scarb test -f tests::cairo_test
          snforge test tests::snforge
          scarb build

      - name: Build and test `strategies`
        working-directory: ./strategies
        run: |
          scarb test -f tests::cairo_test
          snforge test tests::snforge
          scarb build
