name: Tests and linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SCARB_VERSION: 2.3.0

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | bash -s -- -v ${{ env.SCARB_VERSION }}
      - run: cd amm
      - run: scarb test -f tests::cairo_test
      - run: snforge test tests::snforge
      - run: scarb build
      - run: cd ../strategies
      - run: scarb test -f tests::cairo_test
      - run: snforge test tests::snforge
      - run: scarb build
